steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - '-c'
      - >
        gcloud deploy apply --file=./clouddeploy.yaml --region us-central1
        --project=ghost-v4 && gcloud deploy releases create
        release-$BUILD_ID --delivery-pipeline=ghost
        --region=us-central1
    entrypoint: bash
