apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ghost-app
  template:
    metadata:
      labels:
        app: ghost-app
    spec:
      containers:
      - name: ghost-app
        image: ghost
        ports:
        - containerPort: 2368

