apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  root-password: MTIzNDU2 # <base64-encoded-root-password>
  mysql-user: YWRtaW4= # <base64-encoded-mysql-user>
  mysql-password: MTIzNDU2 # <base64-encoded-mysql-password>
